[package]

name = "meza"

version = "0.1.0"

edition = "2021"

license = "MIT"

description = "Meza is a library for data manipulation in Rust."

repository = "https://github.com/stelar-labs/meza-rs"

readme = "README.md"

[dependencies]
